### ISSUE TITLE
Project configuration file

### ISSUE THREAD

**Issue by pingiun** [Fruitscale/Sinas#3]
Sinas needs to be able to recognize project directories. I suggest we do this by looking for a sinas.yaml configuration file.

Yaml is a pretty good choice in my opinion, because advanced users are able to easily read it, and python can also easily read it (using PyYAML).

Let's discuss the format for the configuration file.

**Comment by pingiun** [comment]
```yaml
generator: jekyll # or hugo, eventually
baseurl: https://pingiun.com
host:
  - type: github
    repo: pingiun/pingiun.com
    private_key: ~/.ssh/private_key
  - type: sftp
    host: myhost.io
    user: user
    password: plaintextpasswordmaybe
```
